language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database kouleur_data_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: yG/RekXSXt6EX5tNFpR85rYmPpB8r0/Lt3X1GmT3yLsX3uctcnhbaSwXjuLABjahDr3c8Q5omzeaho2tDK0BRqWvfJP31BdpFqHrI722z0dFf4x1BOEOUEwnEykm9mb6+skO5q/IehHgf8UdoCdbi43DPvX+M9+xK9gd3rPZ7Oz3ixFgTdxmsd679uwUGmntoUEZlZMCPezFxIDWFFoU8BeJVQ9K9CQgOcKXocnWpRg/IQunXymK4FiiQQZkrnPxMgj+lS3YMS6yJzO+znld/NmUPVB5Dsxnq1ulLVqsl4WPNJxvA0FiBx6BVqU/k5aOxnzaN6bZzyRAMKYNWZMC3iyeCMrHMGFt8oAs6CHyZBrbjD92aHffBoDcqRD/IKwJdIkWDY8/FrM9ZAlz+4E0nk4pzEByyEPSXZI9/Pbc5b3/tgDau/wZmo/Inj97r5Hd/yxmJ7NU2y1Rup954Cavl1NdNdwyMxihdGvHRwJVENmbDGrZ+1F4nHHIMzkuAxQ+G+6+q3N3clOxplBqlApGluYkuoYhX4Mn2QaWKDySrUnQvqCxp0KjSwOGLkWCwWuRI36DnD9YzICUTMnvhHWFZXnIVh34v5ej685v+jtjGrSwM9P7LuTik7HojH2rUFe4pkaA78IfpARzD0+yAQZ2mh1sWSWgOnmlmrWYDDIIZrA=
  app: kouleur-api
  on:
    repo: baldm0mma/kouleur-api
