language: node_js
node_js:
- node
services:
- postgresql
before_script:
- psql -c 'create database kouleur_data_test;' -U postgres
- knex migrate:latest --env=test
- knex seed:run --env=test
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: aRrfq53VYRSV/maM3sFujD7DCxTmvbbHV2NA0R3UJjkPPB9IpnnZAbgTL2hPMAzXY9yr/qhUEuRm9M8HG+kydijxrftZFDw378tEy3O28dfD3k+9CAr8hgKnrwCHouAxapwF6SkqiqueqsJYQPonj2zTuAxCe/ZVCxy9uZ2DdxnV5TL4BCKGHhAdgtaBKCtoYr6OIqz9yUAn9HWO7ZHa+gxkqdW25pXzDoY4VaUkTWpWXloHiVO8w0hMG/30DK/OA7C3NcGaG2MjcDfHFqcbvZteq53oQI/+ayka8SFqJG0HA989ddpPZDTvKW6d263CQwZyUs3UKEdm4jYNZp2VlA48XsiMUL5kJb8r1Pl+hB0VaoxFTyWgJ0fxvnza9ipoFSvPcm22ywBOVEX4KDvYtNo9SdF1tyYkkIbtaZ5jlUd6V2J4uil41QHiYITRj0CkSPsXHLNxItuw+4mi0NkZu5HhupSabMjAc4z/PS/WWCfnbfg84yiZ7K/ul4hRRKVwqeWreJDaBl8z54r+f2rsBPrmF0FPVWuAxDfhUYfnNjLeTYx8N1rPrd/EIZQz6TjANdCDHRPP633aONzWF0Z/7ejeoSFINT7xkryW3EnQerBprnzhsbC+7WXY3MY20vqMQXFaX5zqWFmhoy0ANwcCqQIK5JfHKmVTBvDTAnQzWtc=
  app: kouleur-api
  on:
    repo: baldm0mma/kouleur-api
