language: node_js
node_js:
  - 'node'
services:
  - postgresql
before_script:
  - psql -c 'create database kouleur_data_test;' -U postgres
  - knex migrate:latest --env=test
  - knex seed:run --env=test